package dev.rost.dc.model;

import java.util.List;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@NoArgsConstructor
@Data
@ToString(exclude = {"books", "id"})
@JsonIgnoreProperties({"id", "books"})
@Entity
public class Author {
    @Id
    @GeneratedValue
    UUID id;
    String firstName;
    String patronymic;
    String lastName;

    /**
     * {@link ManyToMany#mappedBy} allows avoid two autogenerated many-to-many join tables
     */
    @ManyToMany(mappedBy = "authors")
    List<Book> books;

    public Author(String firstName, String patronymic, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.patronymic = patronymic;
    }
}
